# Generated by Django 4.1.1 on 2022-09-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default='', max_length=100, unique=True, verbose_name='이메일')),
                ('nickname', models.CharField(default='', max_length=100, unique=True, verbose_name='닉네임')),
                ('name', models.CharField(default='', max_length=100, verbose_name='이름')),
                ('gender', models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=20, verbose_name='성별')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
